[project]
name = "grounding-data"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "vllm>=0.10.2",
]

[dependency-groups]
dev = [
    "pre-commit>=4.3.0",
]
